#!/bin/sh

amxmlc -source-path="libs/" -library-path+="libs/Degrafa_Beta3.swc" -library-path+="libs/ofc2library-k.swc" -library-path+="libs/flexlib.swc" -incremental=true -debug=true src/Collage.mxml
