#!/bin/sh

amxmlc -source-path="src/" -source-path="libs/" -keep-as3-metadata+=Theme,Savable -library-path+="libs/Degrafa_Beta3.swc" -library-path+="libs/as3base64/build/as3base64.swc" -library-path+="libs/map_flex_1_18.swc" -library-path+="libs/AlivePDF.swc" -library-path+="libs/ofc2library-k.swc" -library-path+="libs/flexlib.swc" -library-path+="libs/as3corelib.swc" -incremental=true -debug=true src/Desktop/Collage.mxml
