#!/bin/sh

amxmlc -source-path="libs/" -library-path+="libs/Degrafa_Beta3.swc" -library-path+="libs/map_flex_1_18.swc" -library-path+="libs/AlivePDF.swc" -library-path+="libs/ofc2library-k.swc" -library-path+="libs/flexlib.swc" -library-path+="libs/as3corelib.swc" -debug=true src/Collage.mxml
