#!/bin/sh

mkdir airpackage

cp assets/app-icons/*.png airpackage/
cp src/Collage.xml airpackage/
cp src/Collage.swf airpackage/
cp src/Collage.air airpackage/

cd airpackage

adt -certificate -cn SelfSign -o "Endless Paths" -c US 2048-RSA collagecert.p12 4Sq_gD_ecPi4fEA
adt -package -storetype pkcs12 -keystore collagecert.p12 -storepass 4Sq_gD_ecPi4fEA Collage.air Collage.xml Collage.swf file-128.png icon-128.png

cd ../

cp airpackage/Collage.air ./

rm -rf airpackage